name: Deploy Node.js App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: node-auth-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

    - name: SSH and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
          docker stop node-auth-app || true
          docker rm node-auth-app || true
          docker run -d --env-file /home/${{ secrets.SERVER_USER }}/.env -p 80:3000 --name node-auth-app ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
